os: linux
language: java
services:
  - docker
cache: bundler
dist: focal
install: skip
stages:
  - name: test-branch
jobs:
  include:
    - stage: tests
      name: testing22
      script: exit
after_success:
  - echo passed
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
notifications:
  webhooks:
    urls:
      - url: https://default8498120007044e2c82ffc288b51bc0.12.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/701092b36c7c4baaa8d753ab9a35ddfb/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=vFZExLkjrvmM-_QP94WTMH6QW2x7-hkRGIaG6vGoOPs
        msteams: true
      - https://webhook.site/7748f3e1-168d-4f7e-a0fa-f2aab85d206b
    on_success: change
    on_failure: change
